package com.hoodie.app.domain.daystate

enum class DayStateReason {
    WAKE_PHONE, WAKE_MOBILITY, WAKE_HOME_EXIT,
    ACTIVE_CONTEXT, ACTIVE_PHONE, ACTIVE_MOVEMENT,
    COMMUTE_CONFIRMED, COMMUTE_INFERRED, ARRIVAL_CONFIRMED, ARRIVAL_INFERRED,
    HOME_LOW_ACTIVITY, BEDTIME_PATTERN, SLEEP_INACTIVITY, SLEEP_CONFIRMED
}
